/*   Created by IntelliJ IDEA.
 *   Author: Devansh Shukla (D-Coder135)
 *   Date: 15-02-2022/02/2022
 *   Time: 09:25 PM
 *   File: AllSubsequence
 */

/**
 * All Subsequences GFG =>
 * <p>
 * Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is
 * generated by deleting some character of a given string without changing its order.
 */

package final450DSA.strings;

public class AllSubsequence {
}
