/*   Created by IntelliJ IDEA.
 *   Author: Devansh Shukla (D-Coder135)
 *   Date: 15-02-2022/02/2022
 *   Time: 09:25 PM
 *   File: AllSubsequence
 */

/**
 * All Subsequences GFG =>
 * <p>
 * Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is
 * generated by deleting some character of a given string without changing its order.
 */

package final450DSA.strings;

import java.util.ArrayList;
import java.util.List;

public class AllSubsequence {

    static List<String> allSubsequ = new ArrayList<>();
    public static List<String> findSubsequences(String str, String ans) {

        if (str.length() == 0) {
            allSubsequ.add(ans);
            return allSubsequ;
        }

        findSubsequences(str.substring(1), ans + str.charAt(0)); // adding first character of the string to the ans.
        findSubsequences(str.substring(1), ans); // not adding the first character of the string to the ans.

        return allSubsequ;
    }

    public static void main(String[] args) {
        String s = "abcd";
        System.out.println(findSubsequences(s, ""));
    }
}
